### ISSUE TITLE
Constantly get 3,3 volts on outputs

### ISSUE THREAD

**Issue by Hjelten** [nebhead/PiFire-Pages#1]
Hello, I’m trying to get this working for the first time. Byt my Auger, fan och igniter starts as soon as I start up. I have Done the wizard several times to check that I chose all the right hardware.
I disconnected the wires between the releay utput on my PiFire 2.0 board and ni matter what i do it is 3.3 volts on the com pins. Any suggestions on what might be wrong or what to look at?
Ive tried to disconnect the board and check if i get connection between those pins and any 3,3v pins on the board but not that I can find atleast.

**Comment by nebhead** [comment]
Do they start when you startup the system or when you click startup in the GUI?  The latter would be normal behavior.  If it's that they all start up when you startup the system, it's likely that the relays are set to active low in the configuration.  

Which version of PiFire do you have installed?

**Comment by Hjelten** [comment]
Yeah Iam really sorry for this. I feel more stupid than usual right now. When I bought the parts I just used the links in the discription and copied the names into the swedish amazon. 
Dident figger until now that active high and active low is the same as normaly open and closed. Thuoght it had something to do with the amaount of voltage needed to open the coil. 
realy sorry for this dumb issue!

**Comment by nebhead** [comment]
Oh no need to apologize!  I think this is the number one issue that people face on this project when they get started.  I probably should make the documentation clearer.  Regardless, I'm super excited that we have someone from Sweden building this project!  I love to see people all over the world building this. Join the Discord and share your build when you get it up and running.  Happy smoking!

**Comment by Hjelten** [comment]
I think I have a faulty relay (have 0v between GPIOs  and gnd  now but the relays still closes as soon as I Connect any GPIO pin to a com pin) so Ill have to order a new one and have another go at it. 

Yeah if I get it to work Ill post some pics👍 the grill/smoker Are an old DIY project that last year got upgraded to include a pellet hopper, with a very basic eBay controller. So when I found this it was a no brainer, of course I DIY smoker should have A DIY controller! And what I have seen so far it seems to be A damn good controller to😃👍
